### ISSUE TITLE
Possible channel offset issue

### ISSUE THREAD

**Issue by dkadrios** [fab672000/MIDIUSB_1x1#1]
Seeing some strange behavior when passing packets from serial in, to usb out.  Channel numbers are being incremented by one.

For instance, a packet on channel 10 (zero index = 9):
Sending the packet out via SendToSerial works fine.  The channel is still 10 on the serial output.
However, when using SendToUSB the channel is 11 when received. 

I believe somewhere in the library an offset compensation is being performed when none is needed.

**Comment by fab672000** [comment]
Thank you, did a blind fix, please let me know if it works for you now.

**Comment by dkadrios** [comment]
Excellent, fix is working great.  Thanks for the quick turnaround :)
