### ISSUE TITLE
Is Sysex support bundeled in?

### ISSUE THREAD

**Issue by ewidance** [fab672000/MIDIUSB_1x1#2]
Hi, 

I try to communicate with a Behringer Bass vamp pro. Regular midi (cc) is ok, put I can't mak sysexdumps working. Is there any limitation with sysex?  Sysex size is 7K. I joined an example of a dump i want to send...

[usine.zip](https://github.com/fab672000/MIDIUSB_1x1/files/2239893/usine.zip)

**Comment by fab672000** [comment]
I did not use sysex so far, this project was made to allow my children to learn piano with their ipads and a old midi digital (casio) piano, for which it is working really great. If you have new use cases and find bugs and could contribute please propose pull requests and I'll review them.
